# make_index.py
# This isn't a test.
# It's a 30 second hack to create an index.html that shows all our tests results.
import os
import glob


TEMPLATE = """
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <title>hordelib Build Images</title>
</head>
<body>
  <h1>hordelib Build Images</h1>
  <p>These are the images generated by the last build</p>
  <div>[images]</div>
</body>
</html>"""


def create_index():
    # Get a list of images
    files = glob.glob("images/*.webp")
    refs = []
    for imagefile in files:
        filename = os.path.basename(imagefile)
        refs.append(f'<a href="{filename}"><image src="{filename}"></a>')
    indexhtml = TEMPLATE.replace("[images]", "".join(refs))
    with open("images/index.html", "wt") as outfile:
        outfile.write(indexhtml)


if __name__ == "__main__":
    create_index()
