name: Test Runner

on: [push, pull_request]

jobs:
  build:

    runs-on: self-hosted
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    env:
      HORDELIB_TESTING: "no-cuda"
    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install --upgrade -r requirements.dev.txt
      - name: Run tox
        run: tox -e tests
      - name: Run a direct run test
        run: python -m tests.run_upscale
      - uses: actions/upload-artifact@v3
        with:
          name: test-images
          path: images/
      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{secrets.S3_BUILD_ARTIFACTS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.S3_BUILD_ARTIFACTS_SECRET_ACCESS_KEY}}
          aws_bucket: hordelib
          source_dir: images/
